Rewrite niri-keys
- Properly search for niri included configs
- Better bind parsing
- Valid json

diff --git a/scripts/niri-keys b/scripts/niri-keys
--- a/scripts/niri-keys
+++ b/scripts/niri-keys
@@ -1,12 +1,6 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-declare -A modvalues
-modvalues[Shift]=1
-modvalues[Control]=4
-modvalues[Alt]=8
-modvalues[Super]=64
-
-declare -a modmask
+declare -a modmasks
 modmasks[0]=""
 modmasks[1]="shift"
 modmasks[4]="control"
@@ -24,108 +18,68 @@ modmasks[73]="mod4-mod1-shift"
 modmasks[76]="mod4-control-mod1"
 modmasks[77]="mod4-control-mod1-shift"
 
-unset printed
-OIFS=$IFS
-IFS=$(printf "\n\b")
-binds=0
-subsection=0
-unset key_combo
-for line in $(cat $HOME/.config/niri/config.kdl); do
-  unset mike
-  if [ -z "$key_combo" ]; then
-    [ $binds = 0 ] && [[ ! $line =~ ^"binds {" ]] && continue
-    binds=1
-    if [[ $line =~ ^[[:space:]]*} ]]; then
-      if [ $subsection != 0 ]; then
-        subsection=$((subsection-1))
-        continue
-      else
-        break
-      fi
-    fi
-    if [ $line = "" ] || [[ $line =~ ^"binds {" ]] || [[ $line =~ ^[[:space:]]*// ]]; then
-      continue
-    fi
+get_niri_includes() {
+  local cfg=${1:-$HOME/.config/niri/config.kdl}
+  local arr=()
 
-    #echo $line
-    [[ $line =~ ^[[:space:]] ]] && line="${line#"${line%%[![:space:]]*}"}"
-    key_combo=${line%% *}
+  # Get list of includes from the niri configuration directory
+  cfg=$(cd "$HOME"/.config/niri 2> /dev/null && realpath "$cfg" 2> /dev/null || return 1)
+  mapfile -t arr < \
+    <(awk '/^\s*include\s/{sub(/^\s*include\s+(optional=[^\s]+)\s+"/,"");sub(/"$/,"");print}' "$cfg")
+  niri_configs+=("$(realpath "$cfg")")
+  for file in "${arr[@]}"; do
+    get_niri_includes "$file"
+  done
+}
 
-    line=${line#* }
-    line="${line#"${line%%[![:space:]]*}"}"
+parse_keybind() {
+  (( $# < 1 )) && return 1
+  local line="$*" keyname key key_combo keybinding desc cmd parts=() modmask=0 scope
 
-    cooldown=0
-    locked=0
-    repeat=1
-    inhibit=1
-    # This isn't working... think of something else
-    while [[ ! $line =~ ^\{ ]] && [[ ! $line =~ ^} ]] ; do
+  # Trim whitespace and remove "binds {" from the beginning
+  line=${line#"${line%%[! ]*}"}
+  line=${line%"${line##*[! ]}"}
+  line=${line#binds \{}
+  line=${line#"${line%%[! ]*}"}
 
-      if [[ $line =~ ^hotkey-overlay-title= ]]; then
-        description=$(echo $line | awk -F'"' '{print $2}')
-        line=$(echo $line | sed -r 's/^hotkey-overlay-title="[^"]*"[[:space:]]+//')
-      elif [[ $line =~ ^allow-when-locked=true ]]; then
-        locked=1
-        line=${line#* }
-      elif [[ $line =~ ^repeat=false ]]; then
-        repeat=0
-        line=${line#* }
-      elif [[ $line =~ ^allow-inhibiting=false ]]; then
-        inhibit=0
-        line=${line#* }
-      elif [[ $line =~ ^cooldown-ms= ]]; then
-        cooldown=$(echo $line | awk -F '[[:space:]=]' '{print $2}')
-        line=${line#* }
-      else
-        line=${line#* }
-      fi
-      #line="${line#"${line%%[![:space:]]*}"}"
-    done
-
-    if [[ $line =~ \{[[:space:]]*(//)*[[:space:]]*$ ]]; then
-      subsection=$((subsection+1))
-      mike=1
-      continue
-    else
-      cmd=$(echo $line | awk -F '[{}]' '{print $2}')
-      cmd="${cmd#"${cmd%%[![:space:]]*}"}"
-      cmd="${cmd%"${cmd##*[![:space:]]}"}"
-      cmd=${cmd%;}
-      [ -z "$description" ] && description=$cmd
-    fi
-  else
-    cmd="${line#"${line%%[![:space:]]*}"}"
-  fi
-
-  [ -n "$mike" ] && echo $mike
-  unset mike
-
-  ## Add code to process keys from sway-i3 script
-  OIFS=$IFS
-  IFS=+
-  modmask=0
-  for key in $key_combo; do
+  # The key is the first part before any spaces
+  key_combo=${line%% *}
+  # Split parts of key_combo
+  IFS=+ read -ra parts <<< "$key_combo"
+  for key in "${parts[@]}"; do
     case $key in
-      Shift|shift)
-        modmask=$((modmask+1))
-        ;;
-      Control|control|Ctrl|ctrl)
-        modmask=$((modmask+4))
-        ;;
-      Alt|alt|Mod1|mod1)
-        modmask=$((modmask+8))
-        ;;
-      Super|super|Mod4|mod4|Mod|mod)
-        modmask=$((modmask+64))
-        ;;
-      *)
-        keybinding=$key
-        ;;
+      [Ss]hift)                modmask=$((modmask+1)) ;;
+      [Cc]ontrol|[Cc]trl)      modmask=$((modmask+4)) ;;
+      [Aa]lt|[Mm]od1)          modmask=$((modmask+8)) ;;
+      [Ss]uper|[Mm]od4|[Mm]od) modmask=$((modmask+64)) ;;
+      *) keybinding=${key/Page_Up/PgUp} ; keybinding=${keybinding/Page_Down/PgDn} ;;
     esac
   done
-  IFS=$OIFS
+  keyname=$(echo "${modmasks[$modmask]:+${modmasks[$modmask]}-}$keybinding" | tr '[:upper:]' '[:lower:]')
+  # Save keylist and modlist for key_combo
+  keylist[$keyname]=$keybinding
+  modlist[$keyname]=${modmasks[$modmask]}
 
-  case $description in
+  # If hotkey-overlay-title is defined, grab it
+  if [[ "$line" == *" hotkey-overlay-title="* ]]; then
+    desc=${line#* hotkey-overlay-title=\"}
+    desc=${desc%%\"*}
+    desc="${desc//\\/\\\\}"
+    desc="${desc//\"/\\\"}"
+  fi
+  desclist[$keyname]=$desc
+
+  # The command is the part between { ... }
+  cmd=${line##*\{}
+  cmd=${cmd# }
+  cmd=${cmd%%\}*}
+  cmd=${cmd% }
+  cmd=${cmd%;}
+  cmd="${cmd//\\/\\\\}"
+  cmd="${cmd//\"/\\\"}"
+  cmdlist[$keyname]=$cmd
+
+  case "$desc" in
     *[Mm]ove[" "-][Ww]indow*|*[Mm]ove[" "-][Cc]olumn*|*"Focus Next Column"*|*"Focus Previous Column"*)
       scope=window
       ;;
@@ -148,28 +102,63 @@ for line in $(cat $HOME/.config/niri/config.kdl); do
       scope=other
       ;;
   esac
+  scopelist[$keyname]=$scope
+}
 
-  if [ "$cmd" = 'spawn "true"' ]; then
-    #echo removing cmd=$cmd>/dev/stderr
-    unset key_combo description cmd modmask keybinding scope
-    continue
+main() {
+  niri_configs=()
+  get_niri_includes "$1"
+
+  declare -A keylist cmdlist desclist modlist scopelist
+
+  in_binds=false
+  for file in "${niri_configs[@]}" foo.kdl; do
+    i=0
+    while IFS= read -r line; do
+      ((i++))
+      # Strip leading and trailing spaces
+      line=${line%%//*}
+      line=${line#"${line%%[! ]*}"}
+      line=${line%"${line##*[! ]}"}
+
+      # Look for lines that have "binds { ... }"
+      [[ "$line" =~ ^binds[[:space:]]+\{.*[^[:space:]]+.*\}$ ]] && parse_keybind "$line" && continue
+
+      # Start looking for binds with "binds {"
+      [[ "$line" =~ ^binds[[:space:]]+\{[[:space:]]*\}$ ]] && continue
+      [[ "$line" =~ ^binds[[:space:]]+\{$ ]] && in_binds=true && continue
+
+      # Stop looking for binds with "}"
+      [[ "$line" =~ ^\}$ ]] && in_binds=false && continue
+
+      # If not looking for binds, continue
+      $in_binds || continue
+
+      # If line is empty or line starts with a comment, continue
+      [[ -z "$line" ]] && continue
+
+      parse_keybind "$line"
+    done < "$file"
+  done
+
+  # Generate JSON output
+  jsons=()
+  for key in "${!keylist[@]}"; do
+    printf -v item '{ "key": "%s", "command": "%s", "description": "%s", "modifiers": "%s", "scope": "%s" }' \
+      "${keylist[$key]}" "${cmdlist[$key]}" "${desclist[$key]}" "${modlist[$key]}" "${scopelist[$key]}"
+    jsons+=("$item")
+  done
+  json=$(IFS=,; echo "[${jsons[*]}]")
+
+  # Check with python json to ensure that the JSON is valid
+  if echo "$json" | python3 -c "import sys, json; json.load(sys.stdin)" 2> /dev/null; then
+    echo "$json"
+  else
+    echo "Error: Could not generate valid json" >&2
+    exit 1
   fi
-  #echo "cmd='$cmd'" > /dev/stderr
-  #echo $keybinding - $modmask - $description - $cmd - $scope > /dev/stderr
-  keybinding=${keybinding/Page_Up/PgUp}
-  keybinding=${keybinding/Page_Down/PgDn}
-  cmd="${cmd//\\/\\\\}"
-  cmd="${cmd//\"/\\\"}"
-  description="${description//\\/\\\\}"
-  description="${description//\"/\\\"}"
-  [ -z "$printed" ] && printf "["
-  printf '%s{ "key": "%s", "command": "%s", "description": "%s", "modifiers": "%s", "scope": "%s" }' \
-    "$printed" "$keybinding" "$cmd" "$description" "${modmasks[$modmask]}" "$scope"
-  printed=", "
+}
 
-  unset key_combo description cmd modmask keybinding scope
-done
-IFS=$OIFS
-
-[ -n "$printed" ] && printf "]\n"
-
+if ! (return 2> /dev/null); then
+  main "$@"
+fi
